# for wheel and imu fusion

frequency: 1
sensor_timeout: 0.1
two_d_mode: true
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true
publish_tf: true
publish_acceleration: false

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map

#odom0: wheel odometry
odom0: odom
odom0_differential: false
odom0_relative: false
odom0_queue_size: 10
odom0_config: [true, true, false,
               false, false, false,
               false , false, false,
               false, false, true,
               false, false, false]

#imu0
imu0: imu/data
imu0_differential: false
imu0_relative: true
imu0_queue_size: 10
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]